### ISSUE TITLE
Vulnerability Assessment Using Metrics spam

### ISSUE THREAD

**Issue by progers** [samaritan/samaritan.github.io#1]
The following posts were made to chromium's security-dev group:
https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/ZWc6wgzNfRY
https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/IX-0a0NxRLw

These findings do not seem useful.

**Comment by nuthanmunaiah** [comment]
@progers 

Thank you for reaching out. The usefulness of the findings is one of the aspects I am evaluating in my research. The overwhelming response to my feedback from the Chromium project has been that these findings are _spam_. I started a thread on [chromium-dev@](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/nyvytKTFyQc) and [security-dev@](https://groups.google.com/a/chromium.org/d/msg/security-dev/dy_DQDFi82k/uZI-UtYpAAAJ) to understand developers' requirements from security metrics.

~ Nuthan Munaiah
